language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

# makefile create executable in bin and gradle in exe/main
script:
 - ./config ; make -C VCG/
 - ./VCG/gradlew --no-daemon -b VCG/build.gradle mainExecutable
 - ./VCG/bin/VCG 10 2
 - ./VCG/build/exe/main/main 10 2
